_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 300
    # ANCHOR_SIZES: (128, 256, 512)
  ROI_HEADS:
    NUM_CLASSES: 8
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
DATASETS:
  TRAIN: ("cityscape_2007_train_t",)
  TEST: ("cityscape_2007_test_t",)
SOLVER:
  STEPS: (40000, 50000)
  MAX_ITER: 60000
  # WARMUP_ITERS: 200
  BASE_LR: 0.001
  IMS_PER_BATCH: 1
OUTPUT_DIR: "city_baseline"